resolver 127.0.0.11 valid=30s;

server {
    listen 80;

    # Serve static frontend files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }

    # Proxy /api/students (all + filter)
    location /api/students {
        proxy_pass http://api:5000/students;
        proxy_set_header Host $host;
    }

    # Proxy /api/top (leaderboard)
    location /api/top {
        proxy_pass http://api:5000/students/top;
        proxy_set_header Host $host;
    }

    # Proxy /api/gpa-by-major
    location /api/gpa-by-major {
        proxy_pass http://api:5000/analytics/gpa-by-major;
        proxy_set_header Host $host;
    }

    # Proxy /api/gpa-distribution
    location /api/gpa-distribution {
        proxy_pass http://api:5000/analytics/gpa-distribution;
        proxy_set_header Host $host;
    }

    # Proxy /api/summary
    location /api/summary {
        proxy_pass http://api:5000/analytics/summary;
        proxy_set_header Host $host;
    }

    # Proxy /api/students-per-major
    location /api/students-per-major {
        proxy_pass http://api:5000/analytics/students-per-major;
        proxy_set_header Host $host;
    }

    # Health check passthrough
    location /api/health {
        proxy_pass http://api:5000/health;
        proxy_set_header Host $host;
    }
}
