CREATE DATABASE IF NOT EXISTS appdb;
USE appdb;

CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  major VARCHAR(100) NOT NULL,
  gpa DECIMAL(3,2) NOT NULL
);

INSERT INTO students (name, major, gpa) VALUES
('Alice Johnson', 'Computer Science', 3.85),
('Bob Martinez', 'Mechanical Engineering', 3.50),
('Carla Singh', 'Economics', 3.92),
('David Lee', 'Biology', 3.70),
('Eva Chen', 'Mathematics', 3.98),
('Frank Nguyen', 'Computer Science', 3.40),
('Grace Kim', 'Psychology', 3.65),
('Henry Patel', 'Chemistry', 3.78),
('Isla Thompson', 'Economics', 3.55),
('James Wilson', 'Biology', 3.20),
('Karen Davis', 'Mathematics', 3.88),
('Leo Brown', 'Computer Science', 3.10),
('Mia Garcia', 'Mechanical Engineering', 3.72),
('Noah Anderson', 'Psychology', 2.95),
('Olivia Taylor', 'Chemistry', 3.60),
('Patrick Harris', 'Economics', 3.45),
('Quinn Robinson', 'Computer Science', 3.92),
('Rachel Lewis', 'Biology', 3.35),
('Samuel Walker', 'Mathematics', 3.80),
('Tara Hall', 'Psychology', 3.55),
('Uma Allen', 'Computer Science', 3.68),
('Victor Young', 'Chemistry', 3.25),
('Wendy King', 'Economics', 3.90),
('Xavier Wright', 'Mechanical Engineering', 3.48),
('Yara Scott', 'Biology', 3.75),
('Zach Green', 'Computer Science', 3.15),
('Aisha Baker', 'Mathematics', 3.95),
('Ben Adams', 'Psychology', 3.30),
('Chloe Nelson', 'Chemistry', 3.62),
('Daniel Carter', 'Economics', 3.42),
('Emily Mitchell', 'Computer Science', 3.88),
('Felix Perez', 'Mechanical Engineering', 3.55),
('Gina Roberts', 'Biology', 3.40),
('Hugo Turner', 'Mathematics', 3.72),
('Iris Phillips', 'Psychology', 3.18),
('Jake Campbell', 'Computer Science', 3.80),
('Kara Parker', 'Chemistry', 3.35),
('Liam Evans', 'Economics', 3.65),
('Maya Edwards', 'Mechanical Engineering', 3.90),
('Nate Collins', 'Biology', 3.28),
('Opal Stewart', 'Computer Science', 3.75),
('Paul Sanchez', 'Mathematics', 3.50),
('Quinn Morris', 'Psychology', 3.82),
('Rose Rogers', 'Chemistry', 3.45),
('Sean Reed', 'Economics', 3.70),
('Tina Cook', 'Computer Science', 3.22),
('Ulric Morgan', 'Mechanical Engineering', 3.60),
('Vera Bell', 'Biology', 3.88),
('Will Murphy', 'Mathematics', 3.38),
('Xena Bailey', 'Psychology', 3.95),
('Yusuf Rivera', 'Computer Science', 3.55),
('Zoe Cooper', 'Chemistry', 3.78),
('Aaron Richardson', 'Economics', 3.32),
('Bella Cox', 'Mechanical Engineering', 3.68),
('Carlos Howard', 'Biology', 3.85),
('Diana Ward', 'Computer Science', 3.42),
('Ethan Torres', 'Mathematics', 3.60),
('Faye Peterson', 'Psychology', 3.75),
('George Gray', 'Chemistry', 3.20),
('Hana Ramirez', 'Economics', 3.90),
('Ivan James', 'Computer Science', 3.48),
('Julia Watson', 'Mechanical Engineering', 3.35),
('Kevin Brooks', 'Biology', 3.72),
('Laura Kelly', 'Mathematics', 3.58),
('Marco Sanders', 'Psychology', 3.88),
('Nina Price', 'Chemistry', 3.25),
('Oscar Bennett', 'Computer Science', 3.65),
('Penny Wood', 'Economics', 3.40),
('Quincy Barnes', 'Mechanical Engineering', 3.80),
('Ruby Ross', 'Biology', 3.52),
('Steve Henderson', 'Mathematics', 3.95),
('Tanya Coleman', 'Psychology', 3.30),
('Ursula Jenkins', 'Computer Science', 3.70),
('Vince Perry', 'Chemistry', 3.45),
('Wendy Powell', 'Economics', 3.82),
('Xander Long', 'Mechanical Engineering', 3.18),
('Yasmine Patterson', 'Biology', 3.60),
('Zeke Hughes', 'Computer Science', 3.38),
('Abby Flores', 'Mathematics', 3.75),
('Bryce Washington', 'Psychology', 3.55),
('Clara Butler', 'Chemistry', 3.90),
('Derek Simmons', 'Economics', 3.28),
('Ella Foster', 'Computer Science', 3.68),
('Finn Gonzalez', 'Mechanical Engineering', 3.85),
('Gemma Bryant', 'Biology', 3.42),
('Hector Alexander', 'Mathematics', 3.62),
('Ingrid Russell', 'Psychology', 3.78),
('Jerome Griffin', 'Computer Science', 3.35),
('Kira Diaz', 'Chemistry', 3.50),
('Logan Hayes', 'Economics', 3.88),
('Mona Ford', 'Mechanical Engineering', 3.22),
('Noel Ford', 'Biology', 3.72),
('Olivia Hamilton', 'Mathematics', 3.45),
('Pedro Graham', 'Psychology', 3.92),
('Queenie Sullivan', 'Computer Science', 3.58),
('Roman Wallace', 'Chemistry', 3.68),
('Sophie Woods', 'Economics', 3.32),
('Theo Cole', 'Mechanical Engineering', 3.80),
('Uma West', 'Biology', 3.48),
('Valentina Jordan', 'Computer Science', 3.95),
('Wade Owens', 'Mathematics', 3.25),
('Xenia Reynolds', 'Psychology', 3.70),
('Yolanda Fisher', 'Chemistry', 3.40),
('Zeus Ellis', 'Economics', 3.85),
('Amber Harrison', 'Computer Science', 3.52),
('Brady Gibson', 'Mechanical Engineering', 3.65),
('Cecile McDonald', 'Biology', 3.38),
('Damon Cruz', 'Mathematics', 3.82),
('Elena Marshall', 'Psychology', 3.20),
('Fabian Ortega', 'Computer Science', 3.75),
('Greta Gomez', 'Chemistry', 3.55),
('Hanson Murray', 'Economics', 3.90),
('Ines Freeman', 'Mechanical Engineering', 3.28),
('Jonas Wells', 'Biology', 3.68),
('Kyla Webb', 'Mathematics', 3.45),
('Lennox Simpson', 'Psychology', 3.88),
('Maria Stevens', 'Computer Science', 3.32),
('Nathan Tucker', 'Chemistry', 3.60),
('Odalys Porter', 'Economics', 3.78),
('Pierce Hunter', 'Mechanical Engineering', 3.42),
('Quintessa Hicks', 'Biology', 3.95),
('Rocco Crawford', 'Mathematics', 3.18),
('Sabrina Henry', 'Psychology', 3.72),
('Tomas Boyd', 'Computer Science', 3.50),
('Uriah Mason', 'Chemistry', 3.35),
('Violet Rice', 'Economics', 3.85),
('Walter Dixon', 'Mechanical Engineering', 3.62),
('Xiomara Medina', 'Biology', 3.48),
('Yannick Hunt', 'Mathematics', 3.80),
('Zara Black', 'Psychology', 3.25),
('Alec Daniels', 'Computer Science', 3.70),
('Bianca Palmer', 'Chemistry', 3.42),
('Clyde Mills', 'Economics', 3.58),
('Demi Holmes', 'Mechanical Engineering', 3.88),
('Edwin Knight', 'Biology', 3.30),
('Francesca Stone', 'Computer Science', 3.75),
('Gerard Warren', 'Mathematics', 3.55),
('Helena Garrett', 'Psychology', 3.92),
('Ignacio Manning', 'Chemistry', 3.22),
('Jade Rhodes', 'Economics', 3.68),
('Kasim Stevenson', 'Mechanical Engineering', 3.45),
('Lydia Burke', 'Biology', 3.82),
('Montgomery Pierce', 'Computer Science', 3.38),
('Nadia Shaw', 'Mathematics', 3.65),
('Orion Harvey', 'Psychology', 3.50),
('Pamela Cunningham', 'Chemistry', 3.90),
('Quinlan Hart', 'Economics', 3.28),
('Regan Ramos', 'Mechanical Engineering', 3.72),
('Sterling Watson', 'Biology', 3.48),
('Tabitha Brooks', 'Computer Science', 3.85),
('Ursula Price', 'Mathematics', 3.32),
('Vincenzo Ross', 'Psychology', 3.70),
('Willa Spencer', 'Chemistry', 3.55),
('Xena Dunn', 'Economics', 3.88),
('Yara Mendez', 'Mechanical Engineering', 3.20),
('Zander Cole', 'Biology', 3.60),
('Adriana Fox', 'Computer Science', 3.78),
('Brendan Bradley', 'Mathematics', 3.42),
('Catalina Wheeler', 'Psychology', 3.95),
('Dominic Hawkins', 'Chemistry', 3.35),
('Eugenia Hoffman', 'Economics', 3.68),
('Fionn Caldwell', 'Mechanical Engineering', 3.52),
('Genevieve Beck', 'Biology', 3.80),
('Hamish Salazar', 'Computer Science', 3.25),
('Isadora Morales', 'Mathematics', 3.72),
('Jasper Mcdonald', 'Psychology', 3.45),
('Kristina Webb', 'Chemistry', 3.88),
('Lachlan Grant', 'Economics', 3.30),
('Mirembe Bridges', 'Mechanical Engineering', 3.65),
('Ophelia Cannon', 'Computer Science', 3.82),
('Phineas Santos', 'Mathematics', 3.18),
('Renata Guerrero', 'Psychology', 3.75),
('Sylvester Ray', 'Chemistry', 3.40),
('Theodora Jacobs', 'Economics', 3.92),
('Ulysses Grant', 'Mechanical Engineering', 3.55),
('Viviana Becker', 'Biology', 3.28),
('Wolfgang Castillo', 'Computer Science', 3.70),
('Xanthippe Walsh', 'Mathematics', 3.45),
('Yolanda Obrien', 'Psychology', 3.85),
('Zephyr Pittman', 'Chemistry', 3.62),
('Alistair Mcbride', 'Economics', 3.38),
('Beatrix Holland', 'Mechanical Engineering', 3.80),
('Cormac Sutton', 'Biology', 3.52),
('Desdemona Waters', 'Computer Science', 3.90),
('Ezekiel Owen', 'Mathematics', 3.25),
('Fiamma Mcintyre', 'Psychology', 3.68),
('Galatea Erickson', 'Chemistry', 3.42),
('Hieronymus Page', 'Economics', 3.78),
('Imogen Mclaughlin', 'Mechanical Engineering', 3.35),
('Jebediah Valdez', 'Biology', 3.95),
('Katarina Walters', 'Computer Science', 3.20),
('Leocadio Bates', 'Mathematics', 3.72),
('Miroslava Salinas', 'Psychology', 3.50),
('Nikoletta Lamb', 'Chemistry', 3.88),
('Octavius Barker', 'Economics', 3.32),
('Persephone Christensen', 'Mechanical Engineering', 3.65),
('Quirinus Pearce', 'Biology', 3.48),
('Rowena Kerr', 'Computer Science', 3.82),
('Seraphina Mcgee', 'Mathematics', 3.22),
('Thaddeus Quinn', 'Psychology', 3.70),
('Valentijn Holt', 'Economics', 3.90),
('Wilhelmina Blanchard', 'Mechanical Engineering', 3.28),
('Xiulan Oneil', 'Biology', 3.60),
('Yevgenia Mccarthy', 'Computer Science', 3.75),
('Zbigniew Strickland', 'Mathematics', 3.40),
('Agnieszka Sandoval', 'Psychology', 3.85),
('Bartholomew Cervantes', 'Chemistry', 3.52),
('Celestyna Williamson', 'Economics', 3.68),
('Dagoberto Barnett', 'Mechanical Engineering', 3.35),
('Ethelinda Lindsey', 'Biology', 3.80),
('Florestan Mcconnell', 'Computer Science', 3.45),
('Grizzelda Casey', 'Mathematics', 3.92),
('Hildegard Mercado', 'Psychology', 3.18),
('Ingomar Calhoun', 'Chemistry', 3.72),
('Jedidiah Holden', 'Economics', 3.48),
('Kunigunde Walton', 'Mechanical Engineering', 3.88),
('Lanzelot Duran', 'Biology', 3.30),
('Nepomuk Garza', 'Mathematics', 3.42),
('Oswaldo Weston', 'Psychology', 3.78),
('Petronilla Byrd', 'Chemistry', 3.25),
('Radegunde Conner', 'Economics', 3.95),
('Sigismund Harrington', 'Mechanical Engineering', 3.58),
('Thecla Pennington', 'Biology', 3.70),
('Venantius Odom', 'Mathematics', 3.85),
('Walburga Branch', 'Psychology', 3.48),
('Xystus Bridges', 'Chemistry', 3.62),
('Yaropolk Noble', 'Economics', 3.38),
('Zenobia Stanton', 'Mechanical Engineering', 3.80),
('Abiodun Rhodes', 'Biology', 3.22),
('Babatunde Schroeder', 'Computer Science', 3.75),
('Chiamaka Pittman', 'Mathematics', 3.50),
('Damaris Haynes', 'Psychology', 3.90),
('Emeka Burgess', 'Chemistry', 3.28),
('Folasade Nash', 'Economics', 3.68),
('Gbolahan Adeyemi', 'Mechanical Engineering', 3.45),
('Hadiza Parks', 'Biology', 3.82),
('Ifeanyi Cannon', 'Computer Science', 3.35),
('Kayode Cobb', 'Psychology', 3.78),
('Leke Pearce', 'Chemistry', 3.42),
('Mopelola Becker', 'Economics', 3.95),
('Nnamdi Cross', 'Mechanical Engineering', 3.18),
('Obiageli Swanson', 'Biology', 3.72),
('Pooja Stanton', 'Computer Science', 3.55),
('Qamar Middleton', 'Mathematics', 3.88),
('Rashida Patel', 'Psychology', 3.25),
('Saoirse Flynn', 'Chemistry', 3.70),
('Tarquin Reeves', 'Economics', 3.40),
('Uche Morrow', 'Mechanical Engineering', 3.85),
('Vashti Fowler', 'Biology', 3.52),
('Yewande Oneil', 'Psychology', 3.80),
('Zaid Malone', 'Chemistry', 3.48),
('Aaliyah Stone', 'Computer Science', 3.65),
('Bjorn Pearson', 'Mechanical Engineering', 3.90),
('Chisom Briggs', 'Biology', 3.28),
('Dragan Kelley', 'Economics', 3.75),
('Eniola Hoover', 'Mathematics', 3.45),
('Freyja Atkins', 'Psychology', 3.88),
('Gunnhild Mendez', 'Chemistry', 3.32),
('Halvar Lucas', 'Computer Science', 3.70),
('Ingrid Weaver', 'Mechanical Engineering', 3.50),
('Jarl Hampton', 'Biology', 3.82),
('Ketill Garner', 'Mathematics', 3.22),
('Leif Watkins', 'Psychology', 3.68),
('Magnus Page', 'Chemistry', 3.42),
('Njord Hardy', 'Economics', 3.85),
('Olaf Pearce', 'Computer Science', 3.55),
('Ragnhild Morrow', 'Mechanical Engineering', 3.78),
('Sigrid Alvarez', 'Biology', 3.38),
('Thorvald Ramos', 'Mathematics', 3.92),
('Ulf Kelley', 'Psychology', 3.25),
('Vigdis Fowler', 'Chemistry', 3.60),
('Yrsa Hoover', 'Economics', 3.48),
('Arjun Sharma', 'Computer Science', 3.80),
('Bhavna Gupta', 'Mechanical Engineering', 3.35),
('Chandra Kumar', 'Biology', 3.95),
('Devika Nair', 'Mathematics', 3.18),
('Esha Reddy', 'Psychology', 3.72),
('Farhan Kapoor', 'Chemistry', 3.50),
('Gauri Mehta', 'Economics', 3.88),
('Harish Verma', 'Computer Science', 3.28),
('Isha Pillai', 'Mechanical Engineering', 3.65),
('Jayesh Krishnan', 'Biology', 3.42),
('Kavitha Subramaniam', 'Mathematics', 3.80),
('Lokesh Iyer', 'Psychology', 3.55),
('Meena Chandrasekaran', 'Chemistry', 3.90),
('Naveen Balakrishnan', 'Economics', 3.32),
('Ojas Bhatt', 'Computer Science', 3.75),
('Padma Venkataraman', 'Mechanical Engineering', 3.48),
('Rahul Trivedi', 'Biology', 3.85),
('Sunita Joshi', 'Mathematics', 3.22),
('Tarun Mishra', 'Psychology', 3.68),
('Usha Pandey', 'Chemistry', 3.45),
('Vikrant Srivastava', 'Economics', 3.92),
('Yamini Bose', 'Computer Science', 3.35),
('Zaheer Agarwal', 'Mechanical Engineering', 3.70),
('Amara Diallo', 'Biology', 3.58),
('Boubacar Camara', 'Mathematics', 3.82),
('Chidinma Okafor', 'Psychology', 3.20),
('Damilola Adekunle', 'Chemistry', 3.75),
('Efua Mensah', 'Economics', 3.42),
('Fatou Seck', 'Computer Science', 3.88),
('Gaoussou Toure', 'Mechanical Engineering', 3.30),
('Hamidou Cisse', 'Biology', 3.65),
('Isatou Jallow', 'Mathematics', 3.50),
('Jendayi Achebe', 'Psychology', 3.78),
('Kemi Adeleke', 'Chemistry', 3.25),
('Lamine Coulibaly', 'Economics', 3.95),
('Mariama Balde', 'Computer Science', 3.40),
('Ndidi Okonkwo', 'Mechanical Engineering', 3.72),
('Priya Nwosu', 'Mathematics', 3.85),
('Ramatou Sow', 'Psychology', 3.32),
('Seydou Traore', 'Chemistry', 3.62),
('Temi Adeyemi', 'Economics', 3.38),
('Usman Aliyu', 'Computer Science', 3.80),
('Viviane Keita', 'Mechanical Engineering', 3.55),
('Wambua Njoroge', 'Biology', 3.90),
('Xolile Dlamini', 'Mathematics', 3.28),
('Yetunde Afolabi', 'Psychology', 3.70),
('Zainab Hussain', 'Chemistry', 3.45),
('Alejandro Herrera', 'Economics', 3.85),
('Beatriz Salazar', 'Computer Science', 3.52),
('Catalina Rojas', 'Mechanical Engineering', 3.68),
('Diego Fuentes', 'Biology', 3.35),
('Esperanza Mendoza', 'Mathematics', 3.92),
('Felipe Vargas', 'Psychology', 3.22),
('Gabriela Restrepo', 'Chemistry', 3.75),
('Hector Jimenez', 'Economics', 3.48),
('Isabella Morales', 'Computer Science', 3.88),
('Jorge Chavez', 'Mechanical Engineering', 3.30),
('Karla Aguilar', 'Biology', 3.65),
('Luis Contreras', 'Mathematics', 3.42),
('Mariana Castillo', 'Psychology', 3.80),
('Nicolas Torres', 'Chemistry', 3.58),
('Paola Vega', 'Economics', 3.95),
('Roberto Delgado', 'Computer Science', 3.25),
('Sofia Rios', 'Mechanical Engineering', 3.72),
('Tomas Guerrero', 'Biology', 3.45),
('Valentina Acosta', 'Mathematics', 3.88),
('Ximena Blanco', 'Psychology', 3.32),
('Yolanda Cruz', 'Chemistry', 3.60),
('Zara Ortiz', 'Economics', 3.78),
('Adrian Popescu', 'Computer Science', 3.40),
('Bianca Ionescu', 'Mechanical Engineering', 3.85),
('Catalin Dumitrescu', 'Biology', 3.52),
('Diana Stanescu', 'Mathematics', 3.68),
('Emil Georgescu', 'Psychology', 3.28),
('Florina Popa', 'Chemistry', 3.82),
('Ioana Dinu', 'Computer Science', 3.75),
('Ion Matei', 'Mechanical Engineering', 3.45),
('Jana Mihai', 'Biology', 3.90),
('Liviu Nica', 'Mathematics', 3.35),
('Mariana Florea', 'Psychology', 3.72),
('Nicu Barbu', 'Chemistry', 3.50),
('Octavia Chirila', 'Economics', 3.88),
('Pavel Dobre', 'Computer Science', 3.25),
('Radu Lungu', 'Mechanical Engineering', 3.65),
('Simona Neagu', 'Biology', 3.42),
('Teodor Vlad', 'Mathematics', 3.80),
('Valentina Rotaru', 'Psychology', 3.55),
('Wanda Ciobanu', 'Chemistry', 3.92),
('Yukiko Tanaka', 'Computer Science', 3.70),
('Zhang Wei', 'Mechanical Engineering', 3.48),
('Aigerim Bekova', 'Biology', 3.85),
('Bolat Seitkali', 'Mathematics', 3.22),
('Daniyar Akhmetov', 'Chemistry', 3.45),
('Erlan Nurlanovich', 'Economics', 3.82),
('Farida Yusupova', 'Computer Science', 3.38),
('Hassan Al-Rashid', 'Biology', 3.52),
('Ibrahim Al-Farsi', 'Mathematics', 3.90),
('Jasmine Al-Hassan', 'Psychology', 3.28),
('Khalid Al-Mansouri', 'Chemistry', 3.65),
('Layla Al-Zahrani', 'Economics', 3.42),
('Mohammed Al-Saud', 'Computer Science', 3.80),
('Nadia Al-Omari', 'Mechanical Engineering', 3.35),
('Omar Al-Faisal', 'Biology', 3.95),
('Rania Al-Khatib', 'Mathematics', 3.18),
('Sami Al-Jaber', 'Psychology', 3.72),
('Tariq Al-Nasser', 'Chemistry', 3.50),
('Yusra Al-Hakim', 'Economics', 3.88),
('Amara Conteh', 'Computer Science', 3.32),
('Binta Kouyate', 'Mechanical Engineering', 3.70),
('Coumba Diop', 'Biology', 3.48),
('Djibril Bah', 'Mathematics', 3.85),
('Fanta Diallo', 'Psychology', 3.22),
('Ibrahima Sy', 'Chemistry', 3.60),
('Khadija Mbaye', 'Economics', 3.78),
('Lamine Sall', 'Computer Science', 3.40),
('Mame Diarra Ndiaye', 'Mechanical Engineering', 3.92),
('Ousmane Gaye', 'Mathematics', 3.68),
('Rokhaya Diouf', 'Psychology', 3.45),
('Seynabou Ndiaye', 'Chemistry', 3.88),
('Thierno Barry', 'Economics', 3.30),
('Yacine Fall', 'Computer Science', 3.75),
('Bilal Chaudhry', 'Computer Science', 3.75),
('Hira Mahmood', 'Mechanical Engineering', 3.48),
('Hamza Sheikh', 'Biology', 3.88),
('Sana Qureshi', 'Mathematics', 3.35),
('Umar Farooq', 'Economics', 3.65),
('Ayesha Rizvi', 'Psychology', 3.92),
('Zain Butt', 'Chemistry', 3.28),
('Maha Siddiqui', 'Computer Science', 3.70),
('Faisal Mirza', 'Mechanical Engineering', 3.55),
('Noor Baig', 'Biology', 3.82),
('Saad Nawaz', 'Mathematics', 3.40),
('Maham Iqbal', 'Economics', 3.78),
('Arslan Raza', 'Psychology', 3.22),
('Zara Hashmi', 'Computer Science', 3.68),
('Talha Gillani', 'Chemistry', 3.90),
('Aryan Kapoor', 'Computer Science', 3.72),
('Ishaan Malhotra', 'Mechanical Engineering', 3.58),
('Aditi Sharma', 'Biology', 3.85),
('Riya Bhatia', 'Mathematics', 3.42),
('Vedant Joshi', 'Economics', 3.68),
('Anaya Kulkarni', 'Psychology', 3.90),
('Dhruv Saxena', 'Chemistry', 3.35),
('Nisha Desai', 'Computer Science', 3.78),
('Kabir Mehrotra', 'Mechanical Engineering', 3.52),
('Tanvi Rao', 'Biology', 3.88),
('Shreya Pandey', 'Mathematics', 3.45),
('Aarav Singh', 'Economics', 3.70),
('Diya Chatterjee', 'Psychology', 3.32),
('Vivaan Mishra', 'Chemistry', 3.82),
('Kiara Patel', 'Computer Science', 3.60),
('Yacine Fall', 'Computer Science', 3.75),
('Kofi Asante', 'Biology', 3.62),
('Abena Mensah', 'Mathematics', 3.78),
('Kwame Boateng', 'Computer Science', 3.45),
('Akosua Darko', 'Psychology', 3.88),
('Yaw Amponsah', 'Chemistry', 3.32),
('Adwoa Frimpong', 'Economics', 3.70),
('Kweku Acheampong', 'Mechanical Engineering', 3.55),
('Efua Asante', 'Biology', 3.92),
('Nana Adjei', 'Mathematics', 3.28),
('Ama Owusu', 'Computer Science', 3.65),
('Kojo Mensah', 'Psychology', 3.48),
('Akua Bonsu', 'Chemistry', 3.80),
('Yaa Boakye', 'Economics', 3.35),
('Kwabena Ofori', 'Mechanical Engineering', 3.72),
('Abena Antwi', 'Biology', 3.52),
('Kofi Barimah', 'Mathematics', 3.90),
('Akosua Wiredu', 'Computer Science', 3.22),
('Kwame Appiah', 'Psychology', 3.68),
('Adwoa Asiedu', 'Chemistry', 3.42),
('Linh Nguyen', 'Computer Science', 3.85),
('Minh Tran', 'Mechanical Engineering', 3.50),
('Hoa Pham', 'Economics', 3.75),
('Duc Le', 'Biology', 3.38),
('Lan Vo', 'Mathematics', 3.92),
('Tuan Hoang', 'Psychology', 3.25),
('Mai Dang', 'Chemistry', 3.60),
('Nam Bui', 'Computer Science', 3.78),
('Thu Nguyen', 'Mechanical Engineering', 3.45),
('Huong Trinh', 'Economics', 3.88),
('Ceren Yilmaz', 'Biology', 3.32),
('Emre Kaya', 'Mathematics', 3.70),
('Elif Demir', 'Computer Science', 3.55),
('Burak Celik', 'Psychology', 3.82),
('Selin Arslan', 'Chemistry', 3.28),
('Mert Ozturk', 'Economics', 3.65),
('Ayse Sahin', 'Mechanical Engineering', 3.48),
('Kerem Yildiz', 'Biology', 3.90),
('Zeynep Ozdemir', 'Mathematics', 3.35),
('Baris Koc', 'Computer Science', 3.72),
('Priya Nair', 'Psychology', 3.52),
('Rohan Pillai', 'Chemistry', 3.88),
('Sneha Iyer', 'Economics', 3.25),
('Karthik Menon', 'Computer Science', 3.68),
('Divya Krishnan', 'Mechanical Engineering', 3.42),
('Arun Suresh', 'Biology', 3.80),
('Deepa Varma', 'Mathematics', 3.55),
('Vijay Nambiar', 'Psychology', 3.92),
('Ananya Pillai', 'Chemistry', 3.30),
('Suresh Chandran', 'Economics', 3.70),
('Elena Kovacs', 'Computer Science', 3.48),
('Andras Nagy', 'Mechanical Engineering', 3.85),
('Zsuzsa Horvath', 'Biology', 3.22),
('Bela Varga', 'Mathematics', 3.65),
('Katalin Szabo', 'Psychology', 3.78),
('Istvan Toth', 'Chemistry', 3.40),
('Monika Fekete', 'Economics', 3.92),
('Gabor Papp', 'Computer Science', 3.35),
('Eszter Kiss', 'Mechanical Engineering', 3.72),
('Laszlo Molnar', 'Biology', 3.58),
('Chen Jing', 'Computer Science', 3.88),
('Wang Fang', 'Mathematics', 3.32),
('Liu Yang', 'Psychology', 3.70),
('Zhang Min', 'Chemistry', 3.50),
('Li Xia', 'Economics', 3.82),
('Wu Ling', 'Mechanical Engineering', 3.25),
('Zhao Hui', 'Biology', 3.65),
('Huang Yan', 'Computer Science', 3.45),
('Zhou Mei', 'Mathematics', 3.90),
('Sun Lei', 'Psychology', 3.38),
('Marco Rossi', 'Computer Science', 3.75),
('Giulia Ferrari', 'Mechanical Engineering', 3.52),
('Luca Esposito', 'Economics', 3.88),
('Sofia Romano', 'Biology', 3.28),
('Alessandro Colombo', 'Mathematics', 3.68),
('Martina Ricci', 'Psychology', 3.45),
('Davide Marino', 'Chemistry', 3.80),
('Francesca Bruno', 'Computer Science', 3.35),
('Lorenzo Greco', 'Mechanical Engineering', 3.72),
('Valentina Conti', 'Economics', 3.55),
('Fatima Al-Amin', 'Biology', 3.90),
('Yusuf Osman', 'Mathematics', 3.28),
('Amina Hassan', 'Computer Science', 3.65),
('Ibrahim Musa', 'Psychology', 3.42),
('Halima Abdullahi', 'Chemistry', 3.78),
('Omar Farah', 'Economics', 3.32),
('Hodan Ahmed', 'Mechanical Engineering', 3.85),
('Abdi Warsame', 'Biology', 3.50),
('Safia Jama', 'Mathematics', 3.68),
('Mahad Shire', 'Computer Science', 3.22),
('Jana Novak', 'Psychology', 3.75),
('Petr Dvorak', 'Chemistry', 3.48),
('Katerina Svoboda', 'Economics', 3.88),
('Jakub Kral', 'Mechanical Engineering', 3.30),
('Lucie Blazek', 'Biology', 3.62),
('Tomas Cerny', 'Mathematics', 3.80),
('Marketa Horak', 'Computer Science', 3.45),
('Jan Pospisil', 'Psychology', 3.92),
('Veronika Krejci', 'Chemistry', 3.25),
('Martin Navratil', 'Economics', 3.70),
('Hiroshi Yamamoto', 'Computer Science', 3.55),
('Yuki Watanabe', 'Mechanical Engineering', 3.82),
('Kenji Ito', 'Biology', 3.38),
('Sakura Suzuki', 'Mathematics', 3.68),
('Takeshi Nakamura', 'Psychology', 3.52),
('Aoi Kobayashi', 'Chemistry', 3.90),
('Ryo Kato', 'Economics', 3.28),
('Hana Yamada', 'Computer Science', 3.75),
('Sota Hayashi', 'Mechanical Engineering', 3.45),
('Mia Sato', 'Biology', 3.85),
('Camille Dubois', 'Mathematics', 3.32),
('Lucas Bernard', 'Psychology', 3.72),
('Chloe Martin', 'Chemistry', 3.50),
('Hugo Petit', 'Economics', 3.88),
('Manon Robert', 'Computer Science', 3.25),
('Antoine Simon', 'Mechanical Engineering', 3.65),
('Lea Michel', 'Biology', 3.42),
('Theo Laurent', 'Mathematics', 3.80);
